version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      DB_URL: ${DB_URL:-jdbc:postgresql://wa-postgres:5432/wa_db}
      DB_URL_BASE: ${DB_URL_BASE:-jdbc:postgresql://wa-postgres:5432/wa_db}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-123}
      DB_SCHEMA: ${DB_SCHEMA:-wa_user_service_db}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-wa-kafka:9092}
      JWT_SECRET_ACCESS: ${JWT_SECRET_ACCESS:-Y5ncOVqSI/HnJisBxE0TDsk/3cMP/FbwMDL+elybXkqsmpjNIqbjwCCOM8wTznVkqxeYZqf+ppsr4wzHNt8peA==}
      ENCRYPT_SECRET: ${ENCRYPT_SECRET:-i1Gzkvgov/+JojXyEEIoB8+/204Ow/22EWSQfuAaEwo=}
      CIPHER_ALGORITHM: ${CIPHER_ALGORITHM:-AES/GCM/NoPadding}
      SECRET_KEY_ALGORITHM: ${SECRET_KEY_ALGORITHM:-AES}
      REDIS_HOST: ${REDIS_HOST:-wa-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_TIMEOUT: ${REDIS_TIMEOUT:-5s}
    networks:
      - wa-local-network
    restart: unless-stopped

networks:
  wa-local-network:
    external: true
