spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=wa_user_service_db
    username: postgres
    password: 4589
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres?currentSchema=wa_user_service_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  liquibase:
    enabled: true
    user: postgres
    password: 4589
    default-schema: wa_user_service_db
    liquibase-schema: wa_user_service_db
    change-log: classpath:db/changelog/db.changelog-master.yaml
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      connect-timeout: ${REDIS_TIMEOUT}

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

kafka:
  topics:
    user-registered: ${KAFKA_TOPICS_USER_REGISTERED:user.registered}

jwt:
  secret:
    access: ${JWT_SECRET_ACCESS:Y5ncOVqSI/HnJisBxE0TDsk/3cMP/FbwMDL+elybXkqsmpjNIqbjwCCOM8wTznVkqxeYZqf+ppsr4wzHNt8peA==}

encrypt:
  secret: ${ENCRYPT_SECRET:i1Gzkvgov/+JojXyEEIoB8+/204Ow/22EWSQfuAaEwo=}
  cipher-algorithm: ${CIPHER_ALGORITHM:AES/GCM/NoPadding}
  secret-key-algorithm: ${SECRET_KEY_ALGORITHM:AES}